In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%cd /content/gdrive/My Drive/Github/da-ml-competition

/content/gdrive/My Drive/Github/da-ml-competition


In [3]:
!git config --global user.email "parichaya35@gmail.com"
!git config --global user.name "Filmptz"

In [5]:
import tensorflow as tf
import numpy as np

# Tensor
Tensor คือ x,y ตัวแปรที่ใช้ในการเก็บข้อมูล หรือเป็นค่าคงที่



In [20]:
ts_rank1 = tf.constant([1,2,3]) 
ts_rank2 = tf.constant([[1],[2],[3]]) # matirx 3*1
ts_rank3 = tf.constant([
  [
   [1,2,3],
   [5,6,7]
  ],
  [
   [9,10,11],
   [12,13,14]
  ],
  [
   [15,16,17],
   [18,19,20]
  ]
])

ts_rank4 = tf.ones([3,2,4,5])

In [21]:
ts_rank4

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

# Variable 
Variable คือ ตัวที่สามารถเปลี่ยนค่าไปได้เรื่อยๆ, ตัวที่เราปรับค่าได้ ถ้า operate กัย Tensor คำตอบจะได้ Tensor

In [25]:
var1 = tf.Variable([1,2,3],name = "my variable") # vector size = 3

In [26]:
var1

<tf.Variable 'my variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

# Auto Partial Derivative
only work on variable 

In [30]:
x = tf.Variable(2.0)

with tf.GradientTape() as tape:
  y = x**2
  dy_dx = tape.gradient(y,x)
  print(dy_dx)

tf.Tensor(4.0, shape=(), dtype=float32)


$\mathbb(x)\cdot\mathbb(w)+\mathbb(b)$

In [49]:
w  =tf.Variable(tf.random.normal((3,2)))
b = tf.Variable(tf.zeros(2,dtype=tf.float32))
x = tf.constant([[2.0,1.0,3.0]])
y_true = tf.constant([[5.0,6.0]])
with tf.GradientTape() as tape:
  y_predict = x@w +b
  loss = tf.reduce_mean((y_true-y_predict)**2)
dl_dw,dl_db = tape.gradient(loss,[w,b])

In [50]:
dl_dw,dl_db

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-12.600746, -29.13225 ],
        [ -6.300373, -14.566125],
        [-18.90112 , -43.698376]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -6.300373, -14.566125], dtype=float32)>)

In [53]:
!git add .
!git commit -m "Basic tensorflow"

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean


In [54]:
!git push -u origin master

Branch 'master' set up to track remote branch 'master' from 'origin'.
Everything up-to-date
